imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    assetic.helper.static.class: Mping\CoreBundle\Templating\Helper\AsseticHelper
    assetic.helper.dynamic.class: Mping\CoreBundle\Templating\Helper\AsseticHelper
    session.pdo.db_options:
        db_table:    session
        db_id_col:   id
        db_data_col: value
        db_time_col: time
        
framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['php']
        assets_version: v1013
        form:
            resources:
                - 'MpingCoreBundle:Form'
    default_locale:  "fr"
    trusted_proxies: ~
    session: ~
        #handler_id: session.handler.pdo
    fragments:       ~
    http_method_override: true

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    read_from: web

    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        options:
            1002: "SET NAMES UTF8"
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
