security:
    encoders:
        Mping\CoreBundle\Entity\User: sha1

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        entity_provider:
            entity:
                class: MpingCoreBundle:User
                property: email

    firewalls:
        main:
            switch_user: { role: ROLE_ADMIN, parameter: _switch_user }
            pattern: ^/
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
                user_provider: entity_provider
            form_login:
                csrf_provider: form.csrf_provider
                login_path: /connexion
                check_path: /verification
                use_referer: true
                use_forward: false
                default_target_path: /
                username_parameter: _email
                password_parameter: _password
            logout:
                path: /deconnexion
                target: /
            anonymous: ~

    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # no authentication for the homepage:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(.+), roles: IS_AUTHENTICATED_REMEMBERED }
